apiVersion: v1
kind: Template
metadata:
  name: package-analyzer-imagestream
  annotations:
    description: This is Thoth Core - Package Analyzer ImageStream
    openshift.io/display-name: "Thoth: Package Analyzer ImageStream"
    version: 0.1.3
    tags: poc,thoth,ai-stacks,package-analyzer
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: |-
      This template defines resources needed to deploy Thoth Package
      Analyzer as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: package-analyzer-imagestream
    app: thoth
    component: package-analyzer

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: package-analyzer
      labels:
        app: thoth
        component: package-analyzer
    spec:
      name: latest
      lookupPolicy:
        local: true
